config/routes.rb
QldFisherman::Application.routes.draw do
  resources :comments

  resources :moment_stars

  resources :attachables

  resources :addresses

  resources :messages

  resources :moments

  resources :favourites

  resources :phones

  resources :emails

  resources :friendships

  resources :settings

  resources :locations

  devise_for :users
  resources :users
  resources :species
  resources :species_images
  resources :categories
  resources :locations  
  get "pages/home"
  get "pages/test"
  get "tests/home"
  root to: "pages#home"

end

app/models/moment_star.rb
# == Schema Information
#
# Table name: moment_stars
#
#  id         :integer          not null, primary key
#  moment_id  :integer
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class MomentStar < ActiveRecord::Base
  belongs_to :user
  belongs_to :moment
end

app/controllers/moment_stars_controller.rb
class MomentStarsController < ApplicationController
  before_action :set_moment_star, only: [:show, :edit, :update, :destroy]

  # GET /moment_stars
  # GET /moment_stars.json
  def index
    @moment_stars = MomentStar.all
  end

  # GET /moment_stars/1
  # GET /moment_stars/1.json
  def show
  end

  # GET /moment_stars/new
  def new
    @moment_star = MomentStar.new
  end

  # GET /moment_stars/1/edit
  def edit
  end

  # POST /moment_stars
  # POST /moment_stars.json
  def create
    @moment_star = MomentStar.new(moment_star_params)

    respond_to do |format|
      if @moment_star.save
        format.html { redirect_to @moment_star, notice: 'Moment star was successfully created.' }
        format.json { render action: 'show', status: :created, location: @moment_star }
      else
        format.html { render action: 'new' }
        format.json { render json: @moment_star.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moment_stars/1
  # PATCH/PUT /moment_stars/1.json
  def update
    respond_to do |format|
      if @moment_star.update(moment_star_params)
        format.html { redirect_to @moment_star, notice: 'Moment star was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @moment_star.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moment_stars/1
  # DELETE /moment_stars/1.json
  def destroy
    @moment_star.destroy
    respond_to do |format|
      format.html { redirect_to moment_stars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_moment_star
      @moment_star = MomentStar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def moment_star_params
      params.require(:moment_star).permit(:moment_id, :user_id)
    end
end

app/helpers/moment_stars_helper.rb
module MomentStarsHelper
end

app/views/moment_stars/_form.html.erb
<%= simple_form_for(@moment_star) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :moment_id %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/moment_stars/edit.html.erb
<h1>Editing moment_star</h1>

<%= render 'form' %>

<%= link_to 'Show', @moment_star %> |
<%= link_to 'Back', moment_stars_path %>

app/views/moment_stars/index.html.erb
<h1>Listing moment_stars</h1>

<table>
  <thead>
    <tr>
      <th>Moment</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @moment_stars.each do |moment_star| %>
      <tr>
        <td><%= moment_star.moment_id %></td>
        <td><%= moment_star.user_id %></td>
        <td><%= link_to 'Show', moment_star %></td>
        <td><%= link_to 'Edit', edit_moment_star_path(moment_star) %></td>
        <td><%= link_to 'Destroy', moment_star, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Moment star', new_moment_star_path %>

app/views/moment_stars/new.html.erb
<h1>New moment_star</h1>

<%= render 'form' %>

<%= link_to 'Back', moment_stars_path %>

app/views/moment_stars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Moment:</strong>
  <%= @moment_star.moment_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @moment_star.user_id %>
</p>

<%= link_to 'Edit', edit_moment_star_path(@moment_star) %> |
<%= link_to 'Back', moment_stars_path %>